### ISSUE TITLE
question about the role of "shift"

### ISSUE THREAD

**Issue by 594zyc** [AuCson/SEDST#5]
Hi, 

I'm confused about the role of function "shift" in your code. It seems that you put the generative probability of the z decoder backward one time-step through this function, which is later used to multiply with the z decoder output for the implicit copy score calculation. My question is why should the probability be put one step backward? Since the z decoder output at time t is used to calculate the probability of zt instead of z_(t-1), the shift operation is hard to understand. 

However, when I tried to remove "shift", the performance dropped obviously and became much more unstable. Could you explain the principle behind this operation? Thanks!

**Comment by AuCson** [comment]
Thanks for your interest. The reason is that the the representation at the time step 0 is for the <sos> (start_of_sequence) token: `pz_ae = cuda_(Variable(torch.zeros(1, batch_size, self.embed_size)))`

However, the input to the copy decoder later do not include the <sos> token. So we shift the input by one step.
